sudo: false
language: node_js
node_js:
- "10"
- "11"
cache: npm
script:
  - gulp build
jobs:
  include:
    - stage: GitHub Release
      node_js: "11"
      before_deploy:
        # Set up git user name and tag this commit
        - git config --local user.name "Lu√≠s Leite"
        - git config --local user.email "luis@leite.xyz"
        # write npm version to version.txt file
        - npm run write-version
        # setup vars
        - export GIT_COMMIT_HASH=$(git rev-parse --short=8 HEAD)
        - export GIT_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}       
        - export SERVER_VERSION=$(cat version.txt)
        - export FILENAME_SUFFIX="$SERVER_VERSION-$GIT_COMMIT_HASH-$GIT_BRANCH"
        - git tag $SERVER_VERSION
        # Pack the transpiled source code
        - tar -zcf "cso2-master-server_$FILENAME_SUFFIX.tar.gz" dist package.json package-lock.json LICENSE README.md
      deploy:
        name: "Version $SERVER_VERSION"
        provider: releases
        api_key:
          secure: fy56xoi7op5UKZcFGNFo0iFlQPxbDzMkOD6oHqlbOMgWfjU8HLHb9DLYfNcGv6UoA/d/uD20zHP9iipBGVrLsEJim8hP+IkM1K78VeVE9qg5m+1VJ9rib/Jft4fKZH4D46IdBgueBaIrXRIoBsRg2AWqtWkzFoNVgtdUjCarlB4FsUc9g4+uTSI/euKKhyY7RyKHowgbdSVqPgkDrw09sL86Qbmc3Wfba/YAu/NQ0d+QEnjuhycBluC8xVyI8JT2fpXi776/P40SZON+8EeVjgsZRylUk86ndDO+2yN39s4RhBLjqmPD3tXCvD8lhsDvsdR7on8rPLe9IZKAVoF+SfjFr/n/RT5YujHbqhAMBpx7OesjJ2SVadNHEC0txr6ZxUHgK27Kekiq/nGaGT7M2/C1CHMaPHi7vQk45pFy3WV4zrIAC5PTjtEpgvrQW/cRnbuWZq+46IOU0QS18VJ55yXgHrqHNxl2lNSwTdmzBZeeTQNf2XamS/c4QcTKGLhgBZqUFdy13wCCwegEiE+fMhDoMeC2RyqufLb6pbeQB5fOgTHpq/n9qMg9Gc/X4FfwindPLsrYhMTf2zB4z1CZ2GRdOMkgqWP29OQffDCkwG87mXz1dImyT/Q4crTs1iBJKvXvgTGvNx7CK3XHL4ov2WltNnm3I63QOYQojdmvJeo=
        file: "cso2-master-server_$FILENAME_SUFFIX.tar.gz"
        skip_cleanup: true
        overwrite: true